#! /bin/sh
wmname LG3D &
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor eDP -d I II III IV V VI VII VIII IX X
bspc config border_width 2
bspc config window_gap 12
xrandr --output HDMI-A-0 --mode 1366x768 --right-of eDP
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc rule -a Spotify desktop=^5
bspc rule -a Code desktop=^3
bspc rule -a Brave-browser desktop=^1
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating
~/.config/polybar/./launch.sh --hack
bspc config focus_follows_pointer true
picom --experimental-backends &
bspc config border_width 0
python3 ~/scripts/wall.py
~/scripts/inicio
mate-screensaver

